version: "3.4"


services:
  client:
    build: ./
    environment:
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    command: yarn run start